### ISSUE TITLE
overlayPanel does not render selectOneListbox properly

### ISSUE THREAD

**Issue by JiangHongTiao** [primefaces/themes#10]
When I include selectOneListbox in the overlay panel and I use '**Omega**' theme, it is not rendered properly. 
When I press the button, panel is rendered. However a sub-component in the panel is not. When panel is visible and I do double click on the button, sub-component get's rendered. In the same time, when panel is not rendered and I do double click, sub-component is not rendered (and panel not displayed).

Generated html and computed CSS is the same for both painted/non-painted components.

template I have used: 

    <f:view contentType="text/html">
        <h:head>
            <h:outputStylesheet library="main" name="css/flag-icon.css"/>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Church i17n</title>
            </f:facet>
        </h:head>

        <h:body>
            <p:commandButton id="chooseLangBtn" value="Btn" type="button" />
            <p:overlayPanel id="langPanel" 
                            for="chooseLangBtn" 
                            showCloseIcon="true" 
                            dismissable="true"
                            dynamic="true">
                <p:selectOneListbox id="langSelect" 
                                    value="#{selectOneLanguageView.language}" 
                                    converter="languageConverter" 
                                    var="t" filter="true" 
                                    immediate="true"
                                    filterMatchMode="startsWith">
                    <f:selectItems value="#{languageService.languages}" 
                                   var="lang"
                                   
                                   itemLabel="#{lang.name}" 
                                   itemValue="#{lang}" />

                    <p:column>
                        <h:graphicImage width="22px" alt="#{t.name}" library="main" name="images/flags/var/#{t.code}.svg"/>
                    </p:column>

                    <p:column>
                        <h:outputText value="#{t.name}" />
                    </p:column>
                </p:selectOneListbox>
            </p:overlayPanel>

        </h:body>
    </f:view>`

Here is screenshot:
![](https://i.stack.imgur.com/1AOtu.jpg)

**Comment by kukel** [comment]
What is your PF version? Tried the latest? And on which theme **does** it work?

**Comment by JiangHongTiao** [comment]
Sorry for not putting all information. I have tried Afternoon, Afterdark, Afterwork, Aristo, Home, Flick and Start. It's rendered well there. 

Here is info from my pom.xml:

        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <version>6.1</version>
        </dependency>
        <dependency>
            <groupId>org.primefaces.themes</groupId>
            <artifactId>all-themes</artifactId>
            <version>1.0.10</version>
        </dependency>
        <dependency>
            <groupId>org.primefaces.extensions</groupId>
            <artifactId>primefaces-extensions</artifactId>
            <version>6.1.1</version>
        </dependency>

**Comment by JiangHongTiao** [comment]
...and I'm using Chrome browser. 
Version 62.0.3202.94 (Official Build) (64-bit) on Fedora 26
uname: : Linux localhost.localdomain 4.13.12-200.fc26.x86_64 #1 SMP Wed Nov 8 16:47:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tandraschko** [comment]
Omega is a part of primefaces core.
If the issue is still reproducable, please create a issue here https://github.com/primefaces/primefaces and follow the issue template (we need a runnable example).
