### ISSUE TITLE
Premium Theme Apollo not fully responsive

### ISSUE THREAD

**Issue by Quix0r** [primefaces/themes#11]
I hope this is the right place for reporting bugs for premium themes (which are showcased publicly).

If you navigate to the [data demonstration page](https://www.primefaces.org/apollo/data.xhtml) and switch to responsive mode (320x480), you can see overlapping divs (scroll down a bit) [as shown in screenshot](https://cloud.mxchange.org/s/149vSQYmDeENiuY?path=%2FPrimefaces#/Primefaces/20180614%20-%20Primefaces%20-%20Apollo%20-%20Responsive-mode%20-%20001.png), properly due to static `width`.

I would propose a change here to `min/max-width`. A website is only considered as fully responsive when no horizontal scrollbar exists.

**Comment by tandraschko** [comment]
Please use the forum for premium templates.

**Comment by Quix0r** [comment]
@Quix0r ping!
