### ISSUE TITLE
Sentinel: SentinelMenuRenderer not compatible with Primefaces 6.3.

### ISSUE THREAD

**Issue by martin654** [primefaces/themes#12]
Sentinel in version 2.1.2 is not compatible with Primefaces 6.3 snapshot. 
Commit with ID 791b9f1fbfa29f40c4704f6355828bdeff518a15 changed implementation of src/main/java/org/primefaces/util/WidgetBuilder.java.
https://github.com/primefaces/primefaces/issues/3109

SentinelMenuRenderer used in it's method **encodeScript** method:
`wb.initWithDomReady("Sentinel", menu.resolveWidgetVar(), clientId).finish();`
which was removed in PF 6.3 and it fails in runtime on finding the method.

I think it could be replaced with method call>
`wb.init("Sentinel", menu.resolveWidgetVar(), clientId).finish();`
I tested it locally and it worked. (tested using extended class from SentinelMenuRenderer where I overrided the method encodeScript).

**Comment by tandraschko** [comment]
temp fixed: https://github.com/primefaces/primefaces/commit/b5f540c11761dba77ec33ac3a9e9101808e71f27
