### ISSUE TITLE
Delta theme missing resource

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/themes#3]
There is the issue in delta theme. There is missing ressource in maven library. 

[#|2013-10-09T14:37:02.719+0200|WARNING|glassfish3.1.2|javax.enterprise.resource.webcontainer.jsf.application|_ThreadID=138;_ThreadName=Thread-2;|JSF1064: Unable to find or serve resource, images/fallback_moduleHeader.png, from library, primefaces-delta.|#]

**Comment by Sicaine** [comment]
I would suggest to remove that fallback image. At least for me this hinders us to load primeui through webpack for using webpack with primeng.

The property is in row 27 in the file themes/delta/theme.css

I switched to theme 'bootstrap'. Theme 'delta' is used as default in PrimeNG but bootstrap works and looks quite similiar.

**Comment by cagataycivici** [comment]
Are you using PrimeNG or PrimeFaces?

**Comment by Sicaine** [comment]
I'm trying to use PrimeNG which depends on PrimeUI.

**Comment by cagataycivici** [comment]
I see, this tracker is for PrimeFaces Themes, please use PrimeUI tracker instead. It maintains a fork of this.

https://github.com/primefaces/primeui/issues

**Comment by cagataycivici** [comment]
I've removed the image from PrimeUI delta.
