### ISSUE TITLE
Warning in primefaces.THEME delta

### ISSUE THREAD

**Issue by dilnei** [primefaces/themes#8]
just warning, the image does not exist but is mapped in theme.css

13-Oct-2016 16:31:10.173 WARNING [http-apr-8080-exec-2] com.sun.faces.application.resource.ResourceHandlerImpl.logMissingResource JSF1064: Não foi possível encontrar ou fornecer o recurso, images/fallback_moduleHeader.png, pela biblioteca, primefaces-delta.

**Comment by tandraschko** [comment]
fixed - but not sure if there will be a release in the near future. But you can still build it by source.
